spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moon_style?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: shop
    password: shop123

  application:
    name: moon-style

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

server:
  port: 8089